[versions]
# Plugins
agp = "8.4.1"
blueprint = "0.3.1"
dependencyAnalysis = "1.32.0"
dependencyGraph = "0.8.0"
dependencyGuard = "0.5.0"
dependencyVersions = "0.51.0"
detekt = "1.23.6"
doctor = "0.10.0"
hilt = "2.51.1"
kotlin = "2.0.0"
kover = "0.7.6"
ksp = "2.0.0-1.0.21"
ktlint-cli = "1.3.0"
ktlint-gradle = "12.1.1"
licensee = "1.11.0"
licenses = "0.9.7"
spotless = "6.25.0"
turtle = "0.10.0"

# Libraries
alakazam = "4.5.2"
android-desugaring = "2.0.4"
androidx-activity = "1.9.0"
androidx-annotation = "1.8.0"
androidx-compose-bom = "2024.05.00"
androidx-compose-lint = "1.3.1"
androidx-core = "1.13.1"
androidx-fragment = "1.7.1"
androidx-lifecycle = "2.8.1"
androidx-preference = "1.2.1"
androidx-room = "2.6.1"
androidx-splash = "1.0.1"
androidx-sqlite = "2.4.0"
coil = "2.6.0"
flowpreferences = "1.9.1"
javaxInject = "1"
kotlinx-coroutines = "1.8.1"
kotlinx-datetime = "0.6.0"
kotlinx-immutable = "0.3.7"
kotlinx-serialization = "1.6.3"
material = "1.12.0"
okhttp = "4.12.0"
okio = "3.9.0"
retrofit = "2.11.0"
timber = "5.0.1"
voyager = "1.1.0-beta02"

# Testing
test-androidx-arch = "2.2.0"
test-androidx-coreKtx = "1.5.0"
test-androidx-junit = "1.1.5"
test-androidx-rules = "1.5.0"
test-androidx-runner = "1.5.2"
test-junit = "4.13.2"
test-mockk = "1.13.11"
test-robolectric = "4.12.2"
test-timber = "1.0.1"
test-turbine = "1.1.0"

[libraries]
# Plugins
plugin-agp = { module = "com.android.tools.build:gradle", version.ref = "agp" }
plugin-blueprint = { module = "dev.jonpoulton.blueprint:core", version.ref = "blueprint" }
plugin-compose = { module = "org.jetbrains.kotlin.plugin.compose:org.jetbrains.kotlin.plugin.compose.gradle.plugin", version.ref = "kotlin" }
plugin-dependencyGraph = { module = "com.vanniktech:gradle-dependency-graph-generator-plugin", version.ref = "dependencyGraph" }
plugin-dependencyGuard = { module = "com.dropbox.dependency-guard:com.dropbox.dependency-guard.gradle.plugin", version.ref = "dependencyGuard" }
plugin-detekt = { module = "io.gitlab.arturbosch.detekt:detekt-gradle-plugin", version.ref = "detekt" }
plugin-hilt = { module = "com.google.dagger:hilt-android-gradle-plugin", version.ref = "hilt" }
plugin-kotlin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
plugin-kover = { module = "org.jetbrains.kotlinx:kover-gradle-plugin", version.ref = "kover" }
plugin-ksp = { module = "com.google.devtools.ksp:com.google.devtools.ksp.gradle.plugin", version.ref = "ksp" }
plugin-ktlint = { module = "org.jlleitschuh.gradle:ktlint-gradle", version.ref = "ktlint-gradle" }
plugin-licensee = { module = "app.cash.licensee:licensee-gradle-plugin", version.ref = "licensee" }
plugin-spotless = { module = "com.diffplug.spotless:spotless-plugin-gradle", version.ref = "spotless" }
plugin-turtle = { module = "com.lordcodes.turtle:turtle", version.ref = "turtle" }

# Libraries
alakazam-android-compose = { module = "dev.jonpoulton.alakazam:android-ui-compose", version.ref = "alakazam" }
alakazam-android-core = { module = "dev.jonpoulton.alakazam:android-core", version.ref = "alakazam" }
alakazam-android-prefs = { module = "dev.jonpoulton.alakazam:android-prefs-core", version.ref = "alakazam" }
alakazam-kotlin-compose-annotations = { module = "dev.jonpoulton.alakazam:kotlin-compose-annotations", version.ref = "alakazam" }
alakazam-kotlin-core = { module = "dev.jonpoulton.alakazam:kotlin-core", version.ref = "alakazam" }
alakazam-kotlin-time = { module = "dev.jonpoulton.alakazam:kotlin-time", version.ref = "alakazam" }
android-desugaring = { module = "com.android.tools:desugar_jdk_libs", version.ref = "android-desugaring" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity" }
androidx-activity-core = { module = "androidx.activity:activity", version.ref = "androidx-activity" }
androidx-activity-ktx = { module = "androidx.activity:activity-ktx", version.ref = "androidx-activity" }
androidx-annotation = { module = "androidx.annotation:annotation", version.ref = "androidx-annotation" }
androidx-compose-bom = { module = "androidx.compose:compose-bom", version.ref = "androidx-compose-bom" }
androidx-compose-animation-core = { module = "androidx.compose.animation:animation-core" }
androidx-compose-foundation-core = { module = "androidx.compose.foundation:foundation" }
androidx-compose-foundation-layout = { module = "androidx.compose.foundation:foundation-layout" }
androidx-compose-lint = { module = "com.slack.lint.compose:compose-lint-checks", version.ref = "androidx-compose-lint" }
androidx-compose-material3 = { module = "androidx.compose.material3:material3" }
androidx-compose-material-icons-core = { module = "androidx.compose.material:material-icons-core" }
androidx-compose-material-icons-extended = { module = "androidx.compose.material:material-icons-extended" }
androidx-compose-runtime = { module = "androidx.compose.runtime:runtime" }
androidx-compose-ui-core = { module = "androidx.compose.ui:ui" }
androidx-compose-ui-geometry = { module = "androidx.compose.ui:ui-geometry" }
androidx-compose-ui-graphics = { module = "androidx.compose.ui:ui-graphics" }
androidx-compose-ui-text = { module = "androidx.compose.ui:ui-text" }
androidx-compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
androidx-compose-ui-toolingPreview = { module = "androidx.compose.ui:ui-tooling-preview" }
androidx-compose-ui-unit = { module = "androidx.compose.ui:ui-unit" }
androidx-compose-ui-util = { module = "androidx.compose.ui:ui-util" }
androidx-core = { module = "androidx.core:core", version.ref = "androidx-core" }
androidx-coreKtx = { module = "androidx.core:core-ktx", version.ref = "androidx-core" }
androidx-fragment-ktx = { module = "androidx.fragment:fragment-ktx", version.ref = "androidx-fragment" }
androidx-lifecycle-common = { module = "androidx.lifecycle:lifecycle-common", version.ref = "androidx-lifecycle" }
androidx-lifecycle-runtime-compose = { module = "androidx.lifecycle:lifecycle-runtime-compose", version.ref = "androidx-lifecycle" }
androidx-lifecycle-viewmodel-core = { module = "androidx.lifecycle:lifecycle-viewmodel", version.ref = "androidx-lifecycle" }
androidx-lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "androidx-lifecycle" }
androidx-lifecycle-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "androidx-lifecycle" }
androidx-lifecycle-viewmodel-savedstate = { module = "androidx.lifecycle:lifecycle-viewmodel-savedstate", version.ref = "androidx-lifecycle" }
androidx-preference-ktx = { module = "androidx.preference:preference-ktx", version.ref = "androidx-preference" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "androidx-room" }
androidx-room-common = { module = "androidx.room:room-common", version.ref = "androidx-room" }
androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "androidx-room" }
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "androidx-room" }
androidx-sqlite = { module = "androidx.sqlite:sqlite", version.ref = "androidx-sqlite" }
androidx-splash = { module = "androidx.core:core-splashscreen", version.ref = "androidx-splash" }
coil-base = { module = "io.coil-kt:coil-base", version.ref = "coil" }
coil-compose = { module = "io.coil-kt:coil-compose", version.ref = "coil" }
coil-composeBase = { module = "io.coil-kt:coil-compose-base", version.ref = "coil" }
coil-core = { module = "io.coil-kt:coil", version.ref = "coil" }
dagger-core = { module = "com.google.dagger:dagger", version.ref = "hilt" }
flowpreferences = { module = "com.fredporciuncula:flow-preferences", version.ref = "flowpreferences" }
hilt-core = { module = "com.google.dagger:hilt-core", version.ref = "hilt" }
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
hilt-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "hilt" }
javaxInject = { module = "javax.inject:javax.inject", version.ref = "javaxInject" }
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }
kotlinx-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinx-datetime" }
kotlinx-immutable = { module = "org.jetbrains.kotlinx:kotlinx-collections-immutable", version.ref = "kotlinx-immutable" }
kotlinx-serialization-core = { module = "org.jetbrains.kotlinx:kotlinx-serialization-core", version.ref = "kotlinx-serialization" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }
material = { module = "com.google.android.material:material", version.ref = "material" }
okhttp-core = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
okhttp-logging = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "okhttp" }
okio = { module = "com.squareup.okio:okio", version.ref = "okio" }
retrofit-core = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
retrofit-serialization = { module = "com.squareup.retrofit2:converter-kotlinx-serialization", version.ref = "retrofit" }
timber = { module = "com.jakewharton.timber:timber", version.ref = "timber" }
voyager-core = { module = "cafe.adriel.voyager:voyager-core", version.ref = "voyager" }
voyager-hilt = { module = "cafe.adriel.voyager:voyager-hilt", version.ref = "voyager" }
voyager-navigator = { module = "cafe.adriel.voyager:voyager-navigator", version.ref = "voyager" }

# Testing
test-alakazam-core = { module = "dev.jonpoulton.alakazam:testing-core", version.ref = "alakazam" }
test-alakazam-db = { module = "dev.jonpoulton.alakazam:testing-db", version.ref = "alakazam" }
test-androidx-arch = { module = "androidx.arch.core:core-testing", version.ref = "test-androidx-arch" }
test-androidx-coreKtx = { module = "androidx.test:core-ktx", version.ref = "test-androidx-coreKtx" }
test-androidx-junit = { module = "androidx.test.ext:junit", version.ref = "test-androidx-junit" }
test-androidx-rules = { module = "androidx.test:rules", version.ref = "test-androidx-rules" }
test-androidx-runner = { module = "androidx.test:runner", version.ref = "test-androidx-runner" }
test-hilt = { module = "com.google.dagger:hilt-android-testing", version.ref = "hilt" }
test-junit = { module = "junit:junit", version.ref = "test-junit" }
test-kotlin-common = { module = "org.jetbrains.kotlin:kotlin-test-common", version.ref = "kotlin" }
test-kotlin-junit = { module = "org.jetbrains.kotlin:kotlin-test-junit", version.ref = "kotlin" }
test-kotlinx-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinx-coroutines" }
test-mockk-core = { module = "io.mockk:mockk", version.ref = "test-mockk" }
test-mockk-dsl = { module = "io.mockk:mockk-dsl", version.ref = "test-mockk" }
test-mockk-android = { module = "io.mockk:mockk-android", version.ref = "test-mockk" }
test-okhttp = { module = "com.squareup.okhttp3:mockwebserver", version.ref = "okhttp" }
test-robolectric = { module = "org.robolectric:robolectric", version.ref = "test-robolectric" }
test-timber = { module = "net.lachlanmckee:timber-junit-rule", version.ref = "test-timber" }
test-turbine = { module = "app.cash.turbine:turbine", version.ref = "test-turbine" }

[plugins]
agp-app = { id = "com.android.application", version.ref = "agp" }
agp-lib = { id = "com.android.library", version.ref = "agp" }
dependencyAnalysis = { id = "com.autonomousapps.dependency-analysis", version.ref = "dependencyAnalysis" }
dependencyGuard = { id = "com.dropbox.dependency-guard", version.ref = "dependencyGuard" }
dependencyVersions = { id = "com.github.ben-manes.versions", version.ref = "dependencyVersions" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
doctor = { id = "com.osacky.doctor", version.ref = "doctor" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
kover = { id = "org.jetbrains.kotlinx.kover", version.ref = "kover" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint-gradle" }
licensee = { id = "app.cash.licensee", version.ref = "licensee" }
licenses = { id = "com.jaredsburrows.license", version.ref = "licenses" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
